{% set name = "youtube_dl" %}
{% set version = "2018.12.3" %}

package:
  name: youtube-dl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/youtube_dl/youtube_dl-{{ version }}.tar.gz
  sha256: 4664c1230bf63879178728c6be47c54fb47f3aaf836bf6c2a5f945fbda1194a7

build:
  number: 1000
  entry_points:
    - youtube-dl = youtube_dl:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - youtube_dl
    - youtube_dl.downloader
    - youtube_dl.extractor
    - youtube_dl.postprocessor
  commands:
    - youtube-dl --help

about:
  home: http://rg3.github.io/youtube-dl/
  license: Public Domain
  license_family: OTHER
  license_url: http://unlicense.org
  license_file: LICENSE
  summary: YouTube video downloader
  description: |
      Command-line program to download videos from YouTube.com and other video sites
  doc_url: https://github.com/rg3/youtube-dl/blob/master/README.md#readme
  dev_url: https://github.com/rg3/youtube-dl

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
