{% set name = "youtube_dl" %}
{% set version = "2020.9.20" %}

package:
  name: youtube-dl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/youtube_dl/youtube_dl-{{ version }}.tar.gz
  sha256: 67fb9bfa30f5b8f06227c478a8a6ed04af1f97ad4e81dd7e2ce518df3e275391

build:
  number: 1
  entry_points:
    - youtube-dl = youtube_dl:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - youtube-dl --help
    - pip check
  imports:
    - youtube_dl
    - youtube_dl.downloader
    - youtube_dl.extractor
    - youtube_dl.postprocessor

about:
  home: http://rg3.github.io/youtube-dl/
  license: Public Domain
  license_family: OTHER
  license_url: http://unlicense.org
  license_file: LICENSE
  summary: YouTube video downloader
  description: |
    Command-line program to download videos from YouTube.com and other video sites
  doc_url: https://github.com/rg3/youtube-dl/blob/master/README.md#readme
  dev_url: https://github.com/rg3/youtube-dl

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
