{% set name = "youtube_dl" %}
{% set version = "2019.7.14" %}

package:
  name: youtube-dl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/youtube_dl/youtube_dl-{{ version }}.tar.gz
  sha256: 13d37c6b4ef6d6f2190b70d6ac2e29e4d5f69e6036cf2afeda60825aa13a1a18

build:
  number: 0
  entry_points:
    - youtube-dl = youtube_dl:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - youtube_dl
    - youtube_dl.downloader
    - youtube_dl.extractor
    - youtube_dl.postprocessor
  commands:
    - youtube-dl --help

about:
  home: http://rg3.github.io/youtube-dl/
  license: Public Domain
  license_family: OTHER
  license_url: http://unlicense.org
  license_file: LICENSE
  summary: YouTube video downloader
  description: |
      Command-line program to download videos from YouTube.com and other video sites
  doc_url: https://github.com/rg3/youtube-dl/blob/master/README.md#readme
  dev_url: https://github.com/rg3/youtube-dl

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
