{% set name = "youtube_dl" %}
{% set version = "2018.4.25" %}
{% set sha256 = "a657202f97ae2e64635f365c12890591b3ce29bdae1b9b9966d1c4e76b03d66f" %}

package:
  name: {{ name|replace('_', '-') }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - youtube-dl = youtube_dl:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - youtube_dl
    - youtube_dl.downloader
    - youtube_dl.extractor
    - youtube_dl.postprocessor
  commands:
    - youtube-dl --help

about:
  home: http://rg3.github.io/youtube-dl/
  license: Public Domain
  license_family: OTHER
  license_url: http://unlicense.org
  license_file: LICENSE
  summary: YouTube video downloader
  description: |
      Command-line program to download videos from YouTube.com and other video sites
  doc_url: https://github.com/rg3/youtube-dl/blob/master/README.md#readme
  dev_url: https://github.com/rg3/youtube-dl

extra:
  recipe-maintainers:
    - nehaljwani
