travis:
  secure:
    BINSTAR_TOKEN: NBDMqK+wakcoCD/8zNksknw8tO86HaHjXgKXtEZhwD9cRp4RfNiBx/iUG05NcswgLu9JSoWET0aspP7JQbxYiKm0Aj4U+CGmRWEVICU6ctaGM+7NXj7vRaF9O3OvilZNATqBhrqd+Q19mrQQgT8XQsUw/Atf12XYGbaM5kJpjXbqYrifideS/OkqLv3jgUqnr+7CPpEtfg6Y9lbDvLtlzZVi+oOUdp7mKk2kxc/If8A6tlpIKiD2Uey1hSbO2Lh9xUefs1tTqKxHSkBHIspu8ENsA7e5nqXala+SbOZL/3kf8W854JiKFnGDcmyHzv02PEsF5jAefaoL3GviiKZvvEwnAv0Wn3w04QCrtXqsY2Nw21ZaRfHpR5GWZmC6SusV/anSFoIj8DDjNouOUE0aIrLEibwVdJ8ehkeAXuf57rRLoUPC85oHen1IOJuaDlxe0p78WF8LXdnAZAlYA7hG/bTQmdpZfivVHz7+2pnvMhF9pWEoR78z7AqrE5VpEzpi98Szu6PGXP+2GTlYOk1LUuGvhTX+1RTxhhelL6GffOXIX/GFxQg7hLUOpa/Nx1A9T1Cq7qWxGgKfjRzD314SH2JJjzFMsmOFFYypzQHURp5BPdGRItmhfWcfS3py3SIZEPHfVq/MFokQFA7fCeEOoq+W9zVlPa+p0ntyPrENUYs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
