appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: S+/0mDPBx3MuqdZMAXih+zyl1W0+wn1gRN5xR9RdjevObdsjHYuNgCZaHHgOfhi5LL5qUzwMUWjso21LqaXdEX1qLAPvz1HVCnmYsW3H1F6jVhHMWBYaKnT/258oq/FX2W3qUzEcVl5jUjxdXWS5vZKagmGQiD1vgOpkGKEq00IhhonQmoV6RNz9U6othCV4F2pzlzeCSF1gylH9HuNTQoC0JT+CKw9ntUpj4tx+miB0NPopYawYEI5SxYHWz4UoGt0wAflkSttPPJAh4ztIy3G19Y0WhTXSBpE7mtZjgjErKCvrz1txKYADMD/hrOijvi/6I32sFfmqwwJxDH6KVw+pksTNH5pWZ3lw60OWxYzzpxM7mCf6NFLHwrGbtSE1VnW9Vc2ADsv7gPnyxfrEIg2UaNBUzcxafw/laQ7tO4KiMqX3dsOyR7UGQyDIBJo3BGHr1ACn+h9Y/cttMV47OvgRjs64GXxqKGNwvMXmGchQvJYMVxOXAXMPUdDXsrKzVLiFphQdc0Ecc6NMcldBYHYKAKhGae0o4iOiYuBej50ouFGRGz196fsheGta5G4rmRst+kxDGYsQOecRDtpb+8H4BJE6wWfYXpLA+xaMQockzOwSzmjxwOeRDbfAvBxtDZrUKoDhM4YVB+AqLAFEzHM3qWRAYb1S7GgsK+d1ZD8=}
provider:
  win: azure
